python run_dtpaynt.py dts-uai/undiscounted/consensus-4-2 --max_depth 1 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/consensus-4-2 --max_depth 2 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/consensus-4-2 --max_depth 3 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/consensus-4-2 --max_depth 4 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/consensus-4-2 --max_depth 5 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/csma-3-2-some --max_depth 1 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/csma-3-2-some --max_depth 2 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/csma-3-2-some --max_depth 3 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/csma-3-2-some --max_depth 4 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/csma-3-2-some --max_depth 5 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/csma-3-4 --max_depth 1 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/csma-3-4 --max_depth 2 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/csma-3-4 --max_depth 3 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/csma-3-4 --max_depth 4 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/csma-3-4 --max_depth 5 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/firewire-false-36-200 --max_depth 1 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/firewire-false-36-200 --max_depth 2 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/firewire-false-36-200 --max_depth 3 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/firewire-false-36-200 --max_depth 4 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/firewire-false-36-200 --max_depth 5 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/firewire-true-3-600 --max_depth 1 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/firewire-true-3-600 --max_depth 2 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/firewire-true-3-600 --max_depth 3 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/firewire-true-3-600 --max_depth 4 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/firewire-true-3-600 --max_depth 5 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/ij-14-single --max_depth 1 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/ij-14-single --max_depth 2 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/ij-14-single --max_depth 3 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/ij-14-single --max_depth 4 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/ij-14-single --max_depth 5 --time_limit 1200
python run_dtpaynt.py dts-uai/discounted/maze-7 --max_depth 1 --time_limit 1200
python run_dtpaynt.py dts-uai/discounted/maze-7 --max_depth 2 --time_limit 1200
python run_dtpaynt.py dts-uai/discounted/maze-7 --max_depth 3 --time_limit 1200
python run_dtpaynt.py dts-uai/discounted/maze-7 --max_depth 4 --time_limit 1200
python run_dtpaynt.py dts-uai/discounted/maze-7 --max_depth 5 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/wlan-4 --max_depth 1 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/wlan-4 --max_depth 2 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/wlan-4 --max_depth 3 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/wlan-4 --max_depth 4 --time_limit 1200
python run_dtpaynt.py dts-uai/undiscounted/wlan-4 --max_depth 5 --time_limit 1200
