python run_omdt.py mdps/3d_navigation.pickle --max_depth 1 --time_limit 300
python run_omdt.py mdps/3d_navigation.pickle --max_depth 2 --time_limit 300
python run_omdt.py mdps/3d_navigation.pickle --max_depth 3 --time_limit 300
python run_omdt.py mdps/3d_navigation.pickle --max_depth 4 --time_limit 300
python run_omdt.py mdps/3d_navigation.pickle --max_depth 5 --time_limit 300
python run_omdt.py mdps/blackjack.pickle --max_depth 1 --time_limit 300
python run_omdt.py mdps/blackjack.pickle --max_depth 2 --time_limit 300
python run_omdt.py mdps/blackjack.pickle --max_depth 3 --time_limit 300
python run_omdt.py mdps/blackjack.pickle --max_depth 4 --time_limit 300
python run_omdt.py mdps/blackjack.pickle --max_depth 5 --time_limit 300
python run_omdt.py mdps/frozenlake_12x12.pickle --max_depth 1 --time_limit 300
python run_omdt.py mdps/frozenlake_12x12.pickle --max_depth 2 --time_limit 300
python run_omdt.py mdps/frozenlake_12x12.pickle --max_depth 3 --time_limit 300
python run_omdt.py mdps/frozenlake_12x12.pickle --max_depth 4 --time_limit 300
python run_omdt.py mdps/frozenlake_12x12.pickle --max_depth 5 --time_limit 300
python run_omdt.py mdps/frozenlake_4x4.pickle --max_depth 1 --time_limit 300
python run_omdt.py mdps/frozenlake_4x4.pickle --max_depth 2 --time_limit 300
python run_omdt.py mdps/frozenlake_4x4.pickle --max_depth 3 --time_limit 300
python run_omdt.py mdps/frozenlake_4x4.pickle --max_depth 4 --time_limit 300
python run_omdt.py mdps/frozenlake_4x4.pickle --max_depth 5 --time_limit 300
python run_omdt.py mdps/frozenlake_8x8.pickle --max_depth 1 --time_limit 300
python run_omdt.py mdps/frozenlake_8x8.pickle --max_depth 2 --time_limit 300
python run_omdt.py mdps/frozenlake_8x8.pickle --max_depth 3 --time_limit 300
python run_omdt.py mdps/frozenlake_8x8.pickle --max_depth 4 --time_limit 300
python run_omdt.py mdps/frozenlake_8x8.pickle --max_depth 5 --time_limit 300
python run_omdt.py mdps/inventory_management.pickle --max_depth 1 --time_limit 300
python run_omdt.py mdps/inventory_management.pickle --max_depth 2 --time_limit 300
python run_omdt.py mdps/inventory_management.pickle --max_depth 3 --time_limit 300
python run_omdt.py mdps/inventory_management.pickle --max_depth 4 --time_limit 300
python run_omdt.py mdps/inventory_management.pickle --max_depth 5 --time_limit 300
python run_omdt.py mdps/system_administrator_1.pickle --max_depth 1 --time_limit 300
python run_omdt.py mdps/system_administrator_1.pickle --max_depth 2 --time_limit 300
python run_omdt.py mdps/system_administrator_1.pickle --max_depth 3 --time_limit 300
python run_omdt.py mdps/system_administrator_1.pickle --max_depth 4 --time_limit 300
python run_omdt.py mdps/system_administrator_1.pickle --max_depth 5 --time_limit 300
python run_omdt.py mdps/system_administrator_2.pickle --max_depth 1 --time_limit 300
python run_omdt.py mdps/system_administrator_2.pickle --max_depth 2 --time_limit 300
python run_omdt.py mdps/system_administrator_2.pickle --max_depth 3 --time_limit 300
python run_omdt.py mdps/system_administrator_2.pickle --max_depth 4 --time_limit 300
python run_omdt.py mdps/system_administrator_2.pickle --max_depth 5 --time_limit 300
python run_omdt.py mdps/system_administrator_tree.pickle --max_depth 1 --time_limit 300
python run_omdt.py mdps/system_administrator_tree.pickle --max_depth 2 --time_limit 300
python run_omdt.py mdps/system_administrator_tree.pickle --max_depth 3 --time_limit 300
python run_omdt.py mdps/system_administrator_tree.pickle --max_depth 4 --time_limit 300
python run_omdt.py mdps/system_administrator_tree.pickle --max_depth 5 --time_limit 300
python run_omdt.py mdps/tictactoe_vs_random.pickle --max_depth 1 --time_limit 300
python run_omdt.py mdps/tictactoe_vs_random.pickle --max_depth 2 --time_limit 300
python run_omdt.py mdps/tictactoe_vs_random.pickle --max_depth 3 --time_limit 300
python run_omdt.py mdps/tictactoe_vs_random.pickle --max_depth 4 --time_limit 300
python run_omdt.py mdps/tictactoe_vs_random.pickle --max_depth 5 --time_limit 300
python run_omdt.py mdps/tiger_vs_antelope.pickle --max_depth 1 --time_limit 300
python run_omdt.py mdps/tiger_vs_antelope.pickle --max_depth 2 --time_limit 300
python run_omdt.py mdps/tiger_vs_antelope.pickle --max_depth 3 --time_limit 300
python run_omdt.py mdps/tiger_vs_antelope.pickle --max_depth 4 --time_limit 300
python run_omdt.py mdps/tiger_vs_antelope.pickle --max_depth 5 --time_limit 300
python run_omdt.py mdps/traffic_intersection.pickle --max_depth 1 --time_limit 300
python run_omdt.py mdps/traffic_intersection.pickle --max_depth 2 --time_limit 300
python run_omdt.py mdps/traffic_intersection.pickle --max_depth 3 --time_limit 300
python run_omdt.py mdps/traffic_intersection.pickle --max_depth 4 --time_limit 300
python run_omdt.py mdps/traffic_intersection.pickle --max_depth 5 --time_limit 300
python run_omdt.py mdps/xor.pickle --max_depth 1 --time_limit 300
python run_omdt.py mdps/xor.pickle --max_depth 2 --time_limit 300
python run_omdt.py mdps/xor.pickle --max_depth 3 --time_limit 300
python run_omdt.py mdps/xor.pickle --max_depth 4 --time_limit 300
python run_omdt.py mdps/xor.pickle --max_depth 5 --time_limit 300
